# Generated by Django 3.1.7 on 2022-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateStatusPrduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание')),
                ('upload', models.FileField(upload_to='status_xlsx/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновление товаров',
            },
        ),
        migrations.CreateModel(
            name='UpdateStatusView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Результаты обновления',
            },
        ),
    ]
