# Generated by Django 3.1.7 on 2022-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eur',
            options={'verbose_name': 'ГРН/EUR', 'verbose_name_plural': 'ГРН/EUR'},
        ),
        migrations.AlterModelOptions(
            name='usd',
            options={'verbose_name': 'ГРН/USD', 'verbose_name_plural': 'ГРН/USD'},
        ),
    ]
