# Generated by Django 3.1.7 on 2021-05-18 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210518_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_sending',
            field=models.TimeField(default=datetime.time, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_sending',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рассылки'),
        ),
    ]
