# Generated by Django 3.1.7 on 2021-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20210519_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Все рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата расслылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подтверждение рассылки'),
        ),
    ]
