# Generated by Django 3.1.7 on 2021-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210524_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='text',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тема'),
        ),
    ]
