# Generated by Django 3.1.7 on 2021-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210511_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
    ]
