# Generated by Django 3.1.7 on 2021-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210511_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
