# Generated by Django 3.1.7 on 2021-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210512_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Оператор доставки'),
        ),
    ]
