# Generated by Django 3.1.7 on 2021-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210513_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Служба доставки'),
        ),
    ]
