# Generated by Django 3.1.7 on 2021-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210514_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, verbose_name='Телефон'),
        ),
    ]
