# Generated by Django 3.1.7 on 2021-05-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210514_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='patronymic',
        ),
    ]
