# Generated by Django 3.1.7 on 2021-06-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210601_1857'),
        ('orders', '0020_auto_20210601_1810'),
    ]

    operations = [
    ]
