# Generated by Django 3.1.7 on 2021-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.PositiveIntegerField(help_text='грн.', null=True, verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(default=0, help_text='Укажите сумму в грн.', null=True, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale',
            field=models.PositiveIntegerField(help_text='грн.', null=True, verbose_name='Оптовая цена'),
        ),
    ]
