# Generated by Django 3.1.7 on 2021-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210413_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Изображение'),
        ),
    ]
