# Generated by Django 3.1.7 on 2021-05-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
    ]
