# Generated by Django 3.1.7 on 2021-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_imagehome_btn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='url'),
        ),
    ]
