# Generated by Django 3.1.7 on 2021-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210514_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='btn_name',
            field=models.CharField(blank=True, default='Подробнее', max_length=50, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
