# Generated by Django 3.1.7 on 2021-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210514_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='up_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Подзаголовок'),
        ),
    ]
