# Generated by Django 3.1.7 on 2021-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210514_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_free',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.IntegerField(default=1, help_text='грн.', null=True, verbose_name='Цена'),
        ),
    ]
