# Generated by Django 3.1.7 on 2021-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210514_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='imagehome',
            name='up_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
    ]
