# Generated by Django 3.1.7 on 2021-05-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210514_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehome',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.news', verbose_name='Новость'),
        ),
    ]
