# Generated by Django 3.1.7 on 2021-06-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_imagehome_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='poster',
            field=models.ImageField(upload_to='category/', verbose_name='Изображение'),
        ),
    ]
