# Generated by Django 3.1.7 on 2021-12-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20211212_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.availability', verbose_name='Наличие'),
        ),
    ]
