# Generated by Django 3.1.7 on 2022-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20211212_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Штрих-код'),
        ),
    ]
