# Generated by Django 3.1.7 on 2022-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Штрих-код'),
        ),
    ]
