# Generated by Django 3.1.7 on 2022-09-22 09:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20220205_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehome',
            options={'ordering': ['-id'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды на главной'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['availability', 'status', '-id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='availability',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='availability',
            name='name_uk',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='btn_name_ru',
            field=models.CharField(blank=True, default='Подробнее', max_length=50, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='btn_name_uk',
            field=models.CharField(blank=True, default='Подробнее', max_length=50, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='up_title_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='imagehome',
            name='up_title_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_free_ru',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_free_uk',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactures_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactures_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_uk',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Под Категория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Под Категория'),
        ),
    ]
