# Generated by Django 3.1.7 on 2022-09-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20220922_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufactures',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactures_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactures_uk',
        ),
    ]
