# Generated by Django 3.1.7 on 2022-10-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20220926_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_free',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_free_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_free_uk',
        ),
    ]
